export const initialState = {
    gameStarted: false,
    lobby: [],
    users: [],
    currentQuestion: {
      id: 1,
      desc: '____ a mangé un burger aux fraises',
      answers: 1,
      type: 'question',
    },
    questionsDeck: [],
    answersDeck: [
      {
        id: 1,
        desc: 'Le slip de Jean-Pierre',
        type: 'answer',
        isSelected: false,
        isPlayed: false,
      },
      {
        id: 2,
        desc: 'Le slip de Jean-Pierre2',
        type: 'answer',
        isSelected: false,
        isPlayed: false,
      },
      {
        id: 3,
        desc: 'Le slip de Jean-Pierre3',
        type: 'answer',
        isSelected: false,
        isPlayed: false,
      },
      {
        id: 4,
        desc: 'Le slip de Jean-Pierre4',
        type: 'answer',
        isSelected: false,
        isPlayed: false,
      },
      {
        id: 5,
        desc: 'Le slip de Jean-Pierre5',
        type: 'answer',
        isSelected: false,
        isPlayed: false,
      },
      {
        id: 6,
        desc: 'Le slip de Jean-Pierre5',
        type: 'answer',
        isSelected: false,
        isPlayed: false,
      },
      {
        id: 7,
        desc: 'Le slip de Jean-Pierre5',
        type: 'answer',
        isSelected: false,
        isPlayed: false,
      },
      {
        id: 8,
        desc: 'Le slip de Jean-Pierre5',
        type: 'answer',
        isSelected: false,
        isPlayed: false,
      },
      {
        id: 9,
        desc: 'Le slip de Jean-Pierre5',
        type: 'answer',
        isSelected: false,
        isPlayed: false,
      },
      {
        id: 10,
        desc: 'Le slip de Jean-Pierre5',
        type: 'answer',
        isSelected: false,
        isPlayed: false,
      },
    ],
  }