// game
export const INIT_SOCKET_CONNECT = 'INIT_SOCKET_CONNECT'
export const SET_NEW_PLAYER = 'SET_NEW_PLAYER'
export const SET_PHASE = 'SET_PHASE'
export const SHOW_MODAL_CARDS = 'SHOW_MODAL_CARDS'
export const SELECT_CARDS = 'SELECT_CARDS'
