export const answerDeck = [
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
];

export const questionDeck = [
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
];