export const answers = [
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
  { text: 'Answer' },
]

export const questions = [
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
  { text: 'Question' },
]
